### ISSUE TITLE
Get original inventory.

### ISSUE THREAD

**Issue by sillkongen** [olizardo47/AWS-Calculator#1]
How would you get your source inventory to run with the script? What do you use to generate that?

**Comment by olizardo47** [comment]
I have uploaded an inventory template you can use. You can adjust the script to fit your own version of inventory after understanding the mappings.

**Comment by olizardo47** [comment]
Also, you will need to input columns K, U, V and Y (Y as "Virtual Server"), U and V are the vCPU and vMem requirements.

**Comment by sillkongen** [comment]
Thanks that's great.
